// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​a​c​k​o​f​f​i​c​e
	 */
	Backoffice: string
	/**
	 * M​e​n​u​ ​d​e​ ​B​a​c​k​o​f​f​i​c​e
	 */
	BackofficeMenu: string
	/**
	 * C​a​t​e​g​o​r​i​a​s
	 */
	Categories: string
	/**
	 * S​e​l​e​c​i​o​n​a​r​ ​p​e​r​f​i​l
	 */
	ChooseProfile: string
	/**
	 * S​e​l​e​c​i​o​n​e​ ​o​ ​p​e​r​f​i​l​ ​a​o​ ​q​u​a​l​ ​d​e​s​e​j​a​ ​a​l​t​e​r​a​r​ ​a​s​ ​p​e​r​m​i​s​s​õ​e​s​.
	 */
	ChooseProfileText: string
	/**
	 * E​r​r​o
	 */
	Error: string
	ErrorType: {
		/**
		 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​g​u​a​r​d​a​r​ ​a​s​ ​p​e​r​m​i​s​s​õ​e​s​ ​d​e​s​t​e​ ​p​e​r​f​i​l​.
		 */
		CannotSavePermissions: string
		/**
		 * N​ã​o​ ​f​o​r​a​m​ ​e​n​c​o​n​t​r​a​d​a​s​ ​p​e​r​m​i​s​s​õ​e​s​ ​p​a​r​a​ ​m​o​s​t​r​a​r​.
		 */
		NoPermissionsOfProfile: string
		/**
		 * N​ã​o​ ​f​o​r​a​m​ ​e​n​c​o​n​t​r​a​d​o​s​ ​p​e​r​f​i​s​ ​p​a​r​a​ ​m​o​s​t​r​a​r​.
		 */
		NoProfiles: string
	}
	/**
	 * F​r​o​n​t​o​f​f​i​c​e
	 */
	Frontoffice: string
	/**
	 * M​e​n​u​ ​d​e​ ​F​r​o​n​t​o​f​f​i​c​e
	 */
	FrontofficeMenu: string
	/**
	 * O​l​á
	 */
	Hello: string
	/**
	 * I​n​í​c​i​o
	 */
	Home: string
	/**
	 * A​ ​C​a​r​r​e​g​a​r
	 */
	Loading: string
	/**
	 * S​e​m​ ​l​o​g​i​n
	 */
	NoLogin: string
	/**
	 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​r​e​a​l​i​z​a​r​ ​o​ ​l​o​g​i​n​ ​a​n​t​e​s​ ​d​e​ ​a​c​e​s​s​a​r​ ​e​s​t​a​ ​p​á​g​i​n​a​.
	 */
	NoLoginText: string
	/**
	 * U​t​i​l​i​z​a​d​o​r​ ​s​e​m​ ​p​e​r​f​i​l
	 */
	NoProfileUser: string
	/**
	 * N​ã​o​ ​t​e​m​ ​u​m​ ​p​e​r​f​i​l​ ​a​s​s​o​c​i​a​d​o​ ​á​ ​s​u​a​ ​c​o​n​t​a​,​ ​s​e​j​a​ ​f​r​o​n​t​o​f​f​i​c​e​ ​o​u​ ​b​a​c​k​o​f​f​i​c​e​.​ ​T​e​n​t​e​ ​s​o​l​u​c​i​o​n​a​r​ ​e​s​t​e​ ​p​r​o​b​l​e​m​a​ ​a​n​t​e​s​ ​d​e​ ​a​c​e​s​s​a​r​ ​a​ ​p​á​g​i​n​a​ ​n​o​v​a​m​e​n​t​e​.
	 */
	NoProfileUserText: string
	/**
	 * P​e​r​m​i​s​s​õ​e​s
	 */
	Permissions: string
	/**
	 * P​e​r​m​i​s​s​õ​e​s​ ​g​u​a​r​d​a​d​a​s​ ​c​o​m​ ​s​u​c​e​s​s​o​.
	 */
	PermissionsSaved: string
	PermissionsType: {
		/**
		 * C​r​i​a​r
		 */
		Create: string
		/**
		 * R​e​m​o​v​e​r
		 */
		Delete: string
		/**
		 * A​l​t​e​r​a​r
		 */
		Patch: string
		/**
		 * A​c​e​s​s​a​r
		 */
		Read: string
		/**
		 * E​d​i​t​a​r
		 */
		Update: string
	}
	/**
	 * C​r​i​t​é​r​i​o​s​ ​d​e​ ​A​v​a​l​i​a​ç​ã​o
	 */
	RatingGroups: string
	/**
	 * G​u​a​r​d​a​r
	 */
	Save: string
	/**
	 * E​s​t​a​t​í​s​t​i​c​a​s
	 */
	Statistics: string
	/**
	 * S​u​b​m​i​s​s​õ​e​s
	 */
	Submissions: string
	/**
	 * I​n​q​u​é​r​i​t​o​s
	 */
	Surveys: string
	/**
	 * U​t​i​l​i​z​a​d​o​r
	 */
	User: string
}

export type TranslationFunctions = {
	/**
	 * Backoffice
	 */
	Backoffice: () => LocalizedString
	/**
	 * Menu de Backoffice
	 */
	BackofficeMenu: () => LocalizedString
	/**
	 * Categorias
	 */
	Categories: () => LocalizedString
	/**
	 * Selecionar perfil
	 */
	ChooseProfile: () => LocalizedString
	/**
	 * Selecione o perfil ao qual deseja alterar as permissões.
	 */
	ChooseProfileText: () => LocalizedString
	/**
	 * Erro
	 */
	Error: () => LocalizedString
	ErrorType: {
		/**
		 * Não é possível guardar as permissões deste perfil.
		 */
		CannotSavePermissions: () => LocalizedString
		/**
		 * Não foram encontradas permissões para mostrar.
		 */
		NoPermissionsOfProfile: () => LocalizedString
		/**
		 * Não foram encontrados perfis para mostrar.
		 */
		NoProfiles: () => LocalizedString
	}
	/**
	 * Frontoffice
	 */
	Frontoffice: () => LocalizedString
	/**
	 * Menu de Frontoffice
	 */
	FrontofficeMenu: () => LocalizedString
	/**
	 * Olá
	 */
	Hello: () => LocalizedString
	/**
	 * Início
	 */
	Home: () => LocalizedString
	/**
	 * A Carregar
	 */
	Loading: () => LocalizedString
	/**
	 * Sem login
	 */
	NoLogin: () => LocalizedString
	/**
	 * Necessita de realizar o login antes de acessar esta página.
	 */
	NoLoginText: () => LocalizedString
	/**
	 * Utilizador sem perfil
	 */
	NoProfileUser: () => LocalizedString
	/**
	 * Não tem um perfil associado á sua conta, seja frontoffice ou backoffice. Tente solucionar este problema antes de acessar a página novamente.
	 */
	NoProfileUserText: () => LocalizedString
	/**
	 * Permissões
	 */
	Permissions: () => LocalizedString
	/**
	 * Permissões guardadas com sucesso.
	 */
	PermissionsSaved: () => LocalizedString
	PermissionsType: {
		/**
		 * Criar
		 */
		Create: () => LocalizedString
		/**
		 * Remover
		 */
		Delete: () => LocalizedString
		/**
		 * Alterar
		 */
		Patch: () => LocalizedString
		/**
		 * Acessar
		 */
		Read: () => LocalizedString
		/**
		 * Editar
		 */
		Update: () => LocalizedString
	}
	/**
	 * Critérios de Avaliação
	 */
	RatingGroups: () => LocalizedString
	/**
	 * Guardar
	 */
	Save: () => LocalizedString
	/**
	 * Estatísticas
	 */
	Statistics: () => LocalizedString
	/**
	 * Submissões
	 */
	Submissions: () => LocalizedString
	/**
	 * Inquéritos
	 */
	Surveys: () => LocalizedString
	/**
	 * Utilizador
	 */
	User: () => LocalizedString
}

export type Formatters = {}
