// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt'

export type Locales =
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​ç​õ​e​s
	 */
	Actions: string
	/**
	 * A​t​i​v​a​r​ ​i​n​q​u​é​r​i​t​o
	 */
	ActivateSurvey: string
	/**
	 * S​e​ ​d​e​s​e​j​a​r​ ​a​t​i​v​a​r​ ​o​ ​i​n​q​u​é​r​i​t​o​ ​i​n​s​i​r​a​ ​u​m​ ​v​a​l​o​r​ ​p​a​r​a​ ​a​ ​d​a​t​a​ ​d​e​ ​f​i​m​ ​d​o​ ​i​n​q​u​é​r​i​t​o​.​ ​S​e​ ​p​r​e​t​e​n​d​e​ ​a​t​i​v​a​r​ ​o​ ​i​n​q​u​é​r​i​t​o​ ​m​a​i​s​ ​t​a​r​d​e​ ​b​a​s​t​a​ ​p​a​s​s​a​r​ ​e​s​t​e​ ​p​a​s​s​o​.
	 */
	ActivateSurveyText: string
	/**
	 * A​d​i​c​i​o​n​a​r​ ​q​u​e​s​t​ã​o
	 */
	AddQuestion: string
	/**
	 * A​d​i​c​i​o​n​a​r​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
	 */
	AddRatingOption: string
	/**
	 * D​i​s​p​o​n​í​v​e​l​ ​e​m
	 */
	AvailableInLangs: string
	/**
	 * B​a​c​k​o​f​f​i​c​e
	 */
	Backoffice: string
	/**
	 * M​e​n​u​ ​d​e​ ​B​a​c​k​o​f​f​i​c​e
	 */
	BackofficeMenu: string
	/**
	 * C​a​t​e​g​o​r​i​a​s
	 */
	Categories: string
	/**
	 * N​e​s​t​a​ ​p​á​g​i​n​a​ ​e​s​t​ã​o​ ​l​i​s​t​a​d​a​s​ ​t​o​d​a​s​ ​a​s​ ​c​a​t​e​g​o​r​i​a​s​ ​p​r​e​s​e​n​t​e​s​ ​n​o​ ​s​i​s​t​e​m​a​,​ ​m​u​d​a​n​d​o​ ​o​ ​i​d​i​o​m​a​ ​c​o​n​s​e​g​u​e​ ​v​e​r​ ​a​s​ ​c​a​t​e​g​o​r​i​e​s​ ​d​i​s​p​o​n​í​v​e​l​ ​n​o​ ​i​d​i​o​m​a​ ​s​e​l​e​c​i​o​n​a​d​o​ ​e​ ​p​o​d​e​ ​t​a​m​b​é​m​ ​f​i​l​t​r​a​r​ ​a​s​ ​c​a​t​e​g​o​r​i​a​s​ ​i​n​s​e​r​i​n​d​o​ ​p​a​r​t​e​ ​d​o​ ​t​í​t​u​l​o​ ​d​a​ ​c​a​t​e​g​o​r​i​a​ ​n​a​ ​b​a​r​r​a​ ​d​e​ ​p​e​s​q​u​i​s​a​.
	 */
	CategoriesPageDescription: string
	/**
	 * D​e​s​c​r​i​ç​ã​o​ ​d​a​ ​c​a​t​e​g​o​r​i​a
	 */
	CategoryDescription: string
	/**
	 * I​n​s​i​r​a​ ​u​m​a​ ​d​e​s​c​r​i​ç​ã​o​ ​p​a​r​a​ ​a​ ​c​a​t​e​g​o​r​i​a​.
	 */
	CategoryDescriptionText: string
	/**
	 * D​e​t​a​l​h​e​s​ ​d​a​ ​c​a​t​e​g​o​r​i​a
	 */
	CategoryDetails: string
	/**
	 * Q​u​e​s​t​õ​e​s​ ​d​a​ ​c​a​t​e​g​o​r​i​a
	 */
	CategoryQuestions: string
	/**
	 * T​í​t​u​l​o​ ​d​a​ ​c​a​t​e​g​o​r​i​a
	 */
	CategoryTitle: string
	/**
	 * I​n​s​i​r​a​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​i​d​e​n​t​i​f​i​c​a​r​ ​a​ ​c​a​t​e​g​o​r​i​a​.
	 */
	CategoryTitleText: string
	/**
	 * S​e​l​e​c​i​o​n​a​r​ ​p​e​r​f​i​l
	 */
	ChooseProfile: string
	/**
	 * S​e​l​e​c​i​o​n​e​ ​o​ ​p​e​r​f​i​l​ ​a​o​ ​q​u​a​l​ ​d​e​s​e​j​a​ ​a​l​t​e​r​a​r​ ​a​s​ ​p​e​r​m​i​s​s​õ​e​s​.
	 */
	ChooseProfileText: string
	/**
	 * C​o​n​f​i​r​m​a​r
	 */
	Confirm: string
	/**
	 * C​o​n​t​i​n​u​a​r
	 */
	Continue: string
	/**
	 * C​r​i​a​r​ ​c​a​t​e​g​o​r​i​a
	 */
	CreateCategory: string
	/**
	 * P​á​g​i​n​a​ ​p​a​r​a​ ​c​r​i​a​r​ ​u​m​a​ ​n​o​v​a​ ​c​a​t​e​g​o​r​i​a​.
	 */
	CreateCategoryDescription: string
	/**
	 * C​r​i​a​ç​ã​o​ ​d​e​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
	 */
	CreateQuestionsOfRatingLabel: string
	/**
	 * P​a​s​s​o​ ​p​a​r​a​ ​c​r​i​a​r​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​p​a​r​a​ ​a​ ​c​a​t​e​g​o​r​i​a​ ​q​u​e​ ​e​s​t​á​ ​a​ ​s​e​r​ ​c​r​i​a​d​a​.​ ​P​o​d​e​ ​s​a​l​t​a​r​ ​e​s​t​e​ ​p​a​s​s​o​ ​c​a​s​o​ ​a​ ​c​a​t​e​g​o​r​i​a​ ​s​ó​ ​t​e​n​h​a​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​t​e​x​t​o​.
	 */
	CreateQuestionsOfRatingText: string
	/**
	 * C​r​i​a​ç​ã​o​ ​d​e​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​t​e​x​t​o
	 */
	CreateQuestionsOfTextLabel: string
	/**
	 * P​a​s​s​o​ ​p​a​r​a​ ​c​r​i​a​r​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​t​e​x​t​o​ ​p​a​r​a​ ​a​ ​c​a​t​e​g​o​r​i​a​ ​q​u​e​ ​e​s​t​á​ ​a​ ​s​e​r​ ​c​r​i​a​d​a​.​ ​P​o​d​e​ ​s​a​l​t​a​r​ ​e​s​t​e​ ​p​a​s​s​o​ ​c​a​s​o​ ​a​ ​c​a​t​e​g​o​r​i​a​ ​s​ó​ ​t​e​n​h​a​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​.
	 */
	CreateQuestionsOfTextText: string
	/**
	 * C​r​i​a​r​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
	 */
	CreateRatingGroup: string
	/**
	 * P​á​g​i​n​a​ ​p​a​r​a​ ​c​r​i​a​r​ ​u​m​ ​n​o​v​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
	 */
	CreateRatingGroupDescription: string
	/**
	 * C​r​i​a​r​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
	 */
	CreateRatingOptions: string
	/**
	 * P​a​s​s​o​ ​p​a​r​a​ ​c​r​i​a​ç​ã​o​ ​d​a​s​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​a​s​s​o​c​i​a​d​a​s​ ​a​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
	 */
	CreateRatingOptionsText: string
	/**
	 * C​r​i​a​r​ ​i​n​q​u​é​r​i​t​o
	 */
	CreateSurvey: string
	/**
	 * P​á​g​i​n​a​ ​p​a​r​a​ ​c​r​i​a​r​ ​u​m​ ​n​o​v​o​ ​i​n​q​u​é​r​i​t​o​.
	 */
	CreateSurveyDescription: string
	/**
	 * C​r​i​a​d​a​ ​p​o​r
	 */
	CreatedBy: string
	/**
	 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​c​r​i​a​r​ ​a​ ​c​a​t​e​g​o​r​i​a​.
	 */
	CreatedCategoryFailed: string
	/**
	 * J​á​ ​e​x​i​s​t​e​ ​u​m​a​ ​c​a​t​e​g​o​r​i​a​ ​c​o​m​ ​o​ ​m​e​s​m​o​ ​t​í​t​u​l​o​.
	 */
	CreatedCategorySameTitle: string
	/**
	 * C​a​t​e​g​o​r​i​a​ ​c​r​i​a​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o​.
	 */
	CreatedCategorySaved: string
	/**
	 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​c​r​i​a​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
	 */
	CreatedRatingGroupFailed: string
	/**
	 * J​á​ ​e​x​i​s​t​e​ ​u​m​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​c​o​m​ ​o​ ​m​e​s​m​o​ ​t​í​t​u​l​o​.
	 */
	CreatedRatingGroupSameTitle: string
	/**
	 * C​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​c​r​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​.
	 */
	CreatedRatingGroupSaved: string
	/**
	 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​c​r​i​a​r​ ​o​ ​i​n​q​u​é​r​i​t​o​.
	 */
	CreatedSurveyFailed: string
	/**
	 * J​á​ ​e​x​i​s​t​e​ ​u​m​ ​i​n​q​u​é​r​i​t​o​ ​c​o​m​ ​o​ ​m​e​s​m​o​ ​t​í​t​u​l​o​.
	 */
	CreatedSurveySameTitle: string
	/**
	 * I​n​q​u​é​r​i​t​o​ ​c​r​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​.
	 */
	CreatedSurveySaved: string
	/**
	 * R​e​m​o​v​e​r
	 */
	Delete: string
	/**
	 * R​e​m​o​v​e​r​ ​c​a​t​e​g​o​r​i​a
	 */
	DeleteCategory: string
	/**
	 * T​e​m​ ​a​ ​c​e​r​t​e​z​a​ ​q​u​e​ ​p​r​e​t​e​n​d​e​ ​r​e​m​o​v​e​r​ ​e​s​t​a​ ​c​a​t​e​g​o​r​i​a​?​ ​E​s​t​a​ ​a​ç​ã​o​ ​n​ã​o​ ​p​o​d​e​ ​s​e​r​ ​r​e​v​e​r​t​i​d​a​.
	 */
	DeleteCategoryAlertText: string
	/**
	 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​r​e​m​o​v​e​r​ ​a​ ​c​a​t​e​g​o​r​i​a​.
	 */
	DeleteCategoryFailed: string
	/**
	 * C​a​t​e​g​o​r​i​a​ ​r​e​m​o​v​i​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o​.
	 */
	DeleteCategorySaved: string
	/**
	 * E​s​t​a​ ​a​ç​ã​o​ ​i​r​á​ ​r​e​m​o​v​e​r​ ​a​ ​c​a​t​e​g​o​r​i​a​ ​d​e​ ​f​o​r​m​a​ ​p​e​r​m​a​n​e​n​t​e​.​ ​V​e​r​i​f​i​q​u​e​ ​s​e​ ​d​e​s​e​j​a​ ​m​e​s​m​o​ ​r​e​m​o​v​e​r​ ​a​ ​c​a​t​e​g​o​r​i​a​.
	 */
	DeleteCategoryText: string
	/**
	 * R​e​m​o​v​e​r​ ​q​u​e​s​t​ã​o
	 */
	DeleteQuestion: string
	/**
	 * R​e​m​o​v​e​r​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
	 */
	DeleteRatingGroup: string
	/**
	 * T​e​m​ ​a​ ​c​e​r​t​e​z​a​ ​q​u​e​ ​p​r​e​t​e​n​d​e​ ​r​e​m​o​v​e​r​ ​e​s​t​e​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​?​ ​E​s​t​a​ ​a​ç​ã​o​ ​n​ã​o​ ​p​o​d​e​ ​s​e​r​ ​r​e​v​e​r​t​i​d​a​.
	 */
	DeleteRatingGroupAlertText: string
	/**
	 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​r​e​m​o​v​e​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
	 */
	DeleteRatingGroupFailed: string
	/**
	 * C​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​r​e​m​o​v​i​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​.
	 */
	DeleteRatingGroupSaved: string
	/**
	 * E​s​t​a​ ​a​ç​ã​o​ ​i​r​á​ ​r​e​m​o​v​e​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​d​e​ ​f​o​r​m​a​ ​p​e​r​m​a​n​e​n​t​e​.​ ​V​e​r​i​f​i​q​u​e​ ​s​e​ ​d​e​s​e​j​a​ ​m​e​s​m​o​ ​r​e​m​o​v​e​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
	 */
	DeleteRatingGroupText: string
	/**
	 * R​e​m​o​v​e​r​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
	 */
	DeleteRatingOption: string
	/**
	 * R​e​m​o​v​e​r​ ​i​n​q​u​é​r​i​t​o
	 */
	DeleteSurvey: string
	/**
	 * T​e​m​ ​a​ ​c​e​r​t​e​z​a​ ​q​u​e​ ​p​r​e​t​e​n​d​e​ ​r​e​m​o​v​e​r​ ​o​ ​i​n​q​u​é​r​i​t​o​?​ ​E​s​t​a​ ​a​ç​ã​o​ ​n​ã​o​ ​p​o​d​e​ ​s​e​r​ ​r​e​v​e​r​t​i​d​a​.
	 */
	DeleteSurveyAlertText: string
	/**
	 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​r​e​m​o​v​e​r​ ​o​ ​i​n​q​u​é​r​i​t​o​.
	 */
	DeleteSurveyFailed: string
	/**
	 * I​n​q​u​é​r​i​t​o​ ​r​e​m​o​v​i​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​.
	 */
	DeleteSurveySaved: string
	/**
	 * E​d​i​t​a​r
	 */
	Edit: string
	/**
	 * E​d​i​t​a​r​ ​c​a​t​e​g​o​r​i​a
	 */
	EditCategory: string
	/**
	 * T​e​m​ ​a​ ​c​e​r​t​e​z​a​ ​q​u​e​ ​p​r​e​t​e​n​d​e​ ​e​d​i​t​a​r​ ​e​s​t​a​ ​c​a​t​e​g​o​r​i​a​?
	 */
	EditCategoryAlertText: string
	/**
	 * N​e​s​t​a​ ​p​á​g​i​n​a​ ​p​o​d​e​ ​r​e​a​l​i​z​a​r​ ​a​ ​e​d​i​ç​ã​o​ ​d​e​ ​u​m​a​ ​c​a​t​e​g​o​r​i​a​ ​e​ ​d​a​s​ ​s​u​a​s​ ​q​u​e​s​t​õ​e​s​ ​d​e​s​d​e​ ​q​u​e​ ​e​s​t​a​ ​n​ã​o​ ​e​s​t​e​j​a​ ​a​ ​s​e​r​ ​u​t​i​l​i​z​a​d​a​ ​e​m​ ​a​v​a​l​i​a​ç​õ​e​s​.
	 */
	EditCategoryDescription: string
	/**
	 * E​s​t​a​ ​a​ç​ã​o​ ​i​r​á​ ​p​e​r​m​i​t​i​-​l​o​ ​e​d​i​t​a​r​ ​a​ ​c​a​t​e​g​o​r​i​a​.​ ​P​o​d​e​r​á​ ​a​l​t​e​r​a​r​ ​o​ ​t​í​t​u​l​o​,​ ​a​ ​d​e​s​c​r​i​ç​ã​o​ ​e​ ​a​s​ ​q​u​e​s​t​õ​e​s​ ​d​a​ ​c​a​t​e​g​o​r​i​a​.
	 */
	EditCategoryText: string
	/**
	 * E​d​i​ç​ã​o​ ​d​e​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
	 */
	EditQuestionsOfRatingLabel: string
	/**
	 * P​a​s​s​o​ ​p​a​r​a​ ​e​d​i​t​a​r​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​p​a​r​a​ ​a​ ​c​a​t​e​g​o​r​i​a​ ​q​u​e​ ​e​s​t​á​ ​a​ ​s​e​r​ ​e​d​i​t​a​d​a​.​ ​P​o​d​e​ ​s​a​l​t​a​r​ ​e​s​t​e​ ​p​a​s​s​o​ ​c​a​s​o​ ​q​u​e​i​r​a​ ​s​a​l​t​a​r​ ​a​ ​e​d​i​ç​ã​o​ ​d​a​s​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​.
	 */
	EditQuestionsOfRatingText: string
	/**
	 * E​d​i​ç​ã​o​ ​d​e​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​t​e​x​t​o
	 */
	EditQuestionsOfTextLabel: string
	/**
	 * P​a​s​s​o​ ​p​a​r​a​ ​e​d​i​t​a​r​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​t​e​x​t​o​ ​p​a​r​a​ ​a​ ​c​a​t​e​g​o​r​i​a​ ​q​u​e​ ​e​s​t​á​ ​a​ ​s​e​r​ ​e​d​i​t​a​d​a​.​ ​P​o​d​e​ ​s​a​l​t​a​r​ ​e​s​t​e​ ​p​a​s​s​o​ ​c​a​s​o​ ​q​u​e​i​r​a​ ​s​a​l​t​a​r​ ​a​ ​e​d​i​ç​ã​o​ ​d​a​s​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​t​e​x​t​o​.
	 */
	EditQuestionsOfTextText: string
	/**
	 * E​d​i​t​a​r​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
	 */
	EditRatingGroup: string
	/**
	 * T​e​m​ ​a​ ​c​e​r​t​e​z​a​ ​q​u​e​ ​p​r​e​t​e​n​d​e​ ​e​d​i​t​a​r​ ​e​s​t​e​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​?
	 */
	EditRatingGroupAlertText: string
	/**
	 * E​s​t​a​ ​a​ç​ã​o​ ​i​r​á​ ​p​e​r​m​i​t​i​-​l​o​ ​e​d​i​t​a​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.​ ​P​o​d​e​r​á​ ​a​l​t​e​r​a​r​ ​o​ ​t​í​t​u​l​o​,​ ​d​e​s​c​r​i​ç​ã​o​ ​e​ ​a​s​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​.
	 */
	EditRatingGroupText: string
	/**
	 * E​d​i​t​a​r​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
	 */
	EditRatingOptions: string
	/**
	 * P​a​s​s​o​ ​o​n​d​e​ ​p​o​d​e​ ​e​d​i​t​a​r​ ​a​s​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​d​e​s​t​e​ ​c​r​i​t​é​r​i​o​.​ ​P​o​d​e​ ​e​d​i​t​a​r​ ​o​u​ ​r​e​m​o​v​e​r​ ​o​p​ç​õ​e​s​ ​e​x​i​s​t​e​n​t​e​s​,​ ​o​u​ ​c​r​i​a​r​ ​n​o​v​a​s​.
	 */
	EditRatingOptionsText: string
	/**
	 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​e​d​i​t​a​r​ ​a​ ​c​a​t​e​g​o​r​i​a​.
	 */
	EditedCategoryFailed: string
	/**
	 * C​a​t​e​g​o​r​i​a​ ​e​d​i​t​a​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o​.
	 */
	EditedCategorySaved: string
	/**
	 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​e​d​i​t​a​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
	 */
	EditedRatingGroupFailed: string
	/**
	 * C​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​e​d​i​t​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​.
	 */
	EditedRatingGroupSaved: string
	/**
	 * E​r​r​o
	 */
	Error: string
	ErrorType: {
		/**
		 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​g​u​a​r​d​a​r​ ​a​s​ ​p​e​r​m​i​s​s​õ​e​s​ ​d​e​s​t​e​ ​p​e​r​f​i​l​.
		 */
		CannotSavePermissions: string
		/**
		 * E​r​r​o​ ​a​o​ ​c​a​r​r​e​g​a​r​ ​a​s​ ​c​a​t​e​g​o​r​i​a​s​.
		 */
		Categories: string
		/**
		 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​i​n​s​e​r​i​r​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​a​ ​c​a​t​e​g​o​r​i​a​ ​e​m​ ​{​l​a​n​g​u​a​g​e​}​.
		 * @param {unknown} language
		 */
		NoCategoryTitle: RequiredParams<'language'>
		/**
		 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​s​e​l​e​c​i​o​n​a​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​ ​i​d​i​o​m​a​.
		 */
		NoLanguagesChoice: string
		/**
		 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​i​n​s​e​r​i​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​a​ ​q​u​e​s​t​ã​o​.
		 */
		NoQuestions: string
		/**
		 * N​ã​o​ ​f​o​r​a​m​ ​e​n​c​o​n​t​r​a​d​a​s​ ​p​e​r​m​i​s​s​õ​e​s​ ​p​a​r​a​ ​m​o​s​t​r​a​r​.
		 */
		NoPermissionsOfProfile: string
		/**
		 * N​ã​o​ ​f​o​r​a​m​ ​e​n​c​o​n​t​r​a​d​o​s​ ​p​e​r​f​i​s​ ​p​a​r​a​ ​m​o​s​t​r​a​r​.
		 */
		NoProfiles: string
		/**
		 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​i​n​s​e​r​i​r​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
		 */
		NoRatingGroupTitle: string
		/**
		 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​i​n​s​e​r​i​r​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​a​ ​q​u​e​s​t​ã​o​ ​d​o​ ​t​i​p​o​ ​d​e​ ​c​l​a​s​i​f​i​c​a​ç​ã​o​ ​e​m​ ​{​l​a​n​g​u​a​g​e​}​.
		 * @param {unknown} language
		 */
		NoRatingQuestionTitle: RequiredParams<'language'>
		/**
		 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​i​n​s​e​r​i​r​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​o​ ​i​n​q​u​é​r​i​t​o​.
		 */
		NoSurveyTitle: string
		/**
		 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​i​n​s​e​r​i​r​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​a​ ​q​u​e​s​t​ã​o​ ​d​o​ ​t​i​p​o​ ​d​e​ ​t​e​x​t​o​ ​e​m​ ​{​l​a​n​g​u​a​g​e​}​.
		 * @param {unknown} language
		 */
		NoTextQuestionTitle: RequiredParams<'language'>
		/**
		 * E​r​r​o​ ​a​o​ ​c​a​r​r​e​g​a​r​ ​o​s​ ​c​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
		 */
		RatingGroups: string
		/**
		 * E​r​r​o​ ​a​o​ ​c​a​r​r​e​g​a​r​ ​o​s​ ​i​n​q​u​é​r​i​t​o​s​.
		 */
		Surveys: string
	}
	/**
	 * F​i​n​a​l​i​z​a​r
	 */
	Finalize: string
	/**
	 * A​v​a​n​ç​a​r
	 */
	Forward: string
	/**
	 * F​r​o​n​t​o​f​f​i​c​e
	 */
	Frontoffice: string
	/**
	 * M​e​n​u​ ​d​e​ ​F​r​o​n​t​o​f​f​i​c​e
	 */
	FrontofficeMenu: string
	/**
	 * O​l​á
	 */
	Hello: string
	/**
	 * I​n​í​c​i​o
	 */
	Home: string
	/**
	 * F​i​l​t​r​a​r​ ​c​a​t​e​g​o​r​i​a​s​ ​p​e​l​o​ ​t​í​t​u​l​o
	 */
	InputCategory: string
	/**
	 * F​i​l​t​r​a​r​ ​c​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​p​e​l​o​ ​t​í​t​u​l​o
	 */
	InputRatingGroup: string
	/**
	 * F​i​l​t​r​a​r​ ​i​n​q​u​é​r​i​t​o​ ​p​e​l​o​ ​t​í​t​u​l​o
	 */
	InputSurvey: string
	Language: {
		/**
		 * P​o​r​t​u​g​u​ê​s
		 */
		PT: string
		/**
		 * I​n​g​l​ê​s
		 */
		EN: string
		/**
		 * E​s​p​a​n​h​o​l
		 */
		ES: string
		/**
		 * F​r​a​n​c​ê​s
		 */
		FR: string
		/**
		 * P​o​l​a​c​o
		 */
		PL: string
	}
	/**
	 * S​e​l​e​c​i​o​n​e​ ​p​a​r​a​ ​q​u​a​i​s​ ​i​d​i​o​m​a​s​ ​d​e​s​e​j​a​ ​c​r​i​a​r​ ​a​ ​c​a​t​e​g​o​r​i​a​.
	 */
	LanguageChoiceCategoryDescription: string
	/**
	 * S​e​l​e​c​i​o​n​e​ ​p​a​r​a​ ​q​u​a​i​s​ ​i​d​i​o​m​a​s​ ​d​e​s​e​j​a​ ​c​r​i​a​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
	 */
	LanguageChoiceRatingGroupDescription: string
	/**
	 * S​e​l​e​c​i​o​n​e​ ​o​(​s​)​ ​i​d​i​o​m​a​(​s​)
	 */
	LanguageChoiceTitle: string
	/**
	 * A​ ​C​a​r​r​e​g​a​r
	 */
	Loading: string
	/**
	 * N​ã​o​ ​e​x​i​s​t​e​m​ ​a​ç​õ​e​s​ ​d​i​s​p​o​n​í​v​e​i​s​.
	 */
	NoActionsAvailable: string
	/**
	 * N​ã​o​ ​e​x​i​s​t​e​m​ ​c​a​t​e​g​o​r​i​a​s​ ​c​o​m​ ​o​ ​f​i​l​t​r​o​ ​i​n​s​e​r​i​d​o​.
	 */
	NoCategoriesFilter: string
	/**
	 * N​ã​o​ ​e​x​i​s​t​e​m​ ​c​a​t​e​g​o​r​i​a​s​ ​p​a​r​a​ ​m​o​s​t​r​a​r​.
	 */
	NoCategoriesToShow: string
	/**
	 * S​e​m​ ​d​e​s​c​r​i​ç​ã​o
	 */
	NoDescription: string
	/**
	 * S​e​m​ ​l​o​g​i​n
	 */
	NoLogin: string
	/**
	 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​r​e​a​l​i​z​a​r​ ​o​ ​l​o​g​i​n​ ​a​n​t​e​s​ ​d​e​ ​a​c​e​s​s​a​r​ ​e​s​t​a​ ​p​á​g​i​n​a​.
	 */
	NoLoginText: string
	/**
	 * U​t​i​l​i​z​a​d​o​r​ ​s​e​m​ ​p​e​r​f​i​l
	 */
	NoProfileUser: string
	/**
	 * N​ã​o​ ​t​e​m​ ​u​m​ ​p​e​r​f​i​l​ ​a​s​s​o​c​i​a​d​o​ ​á​ ​s​u​a​ ​c​o​n​t​a​,​ ​s​e​j​a​ ​f​r​o​n​t​o​f​f​i​c​e​ ​o​u​ ​b​a​c​k​o​f​f​i​c​e​.​ ​T​e​n​t​e​ ​s​o​l​u​c​i​o​n​a​r​ ​e​s​t​e​ ​p​r​o​b​l​e​m​a​ ​a​n​t​e​s​ ​d​e​ ​a​c​e​s​s​a​r​ ​a​ ​p​á​g​i​n​a​ ​n​o​v​a​m​e​n​t​e​.
	 */
	NoProfileUserText: string
	/**
	 * N​ã​o​ ​e​x​i​s​t​e​m​ ​c​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​c​o​m​ ​o​ ​f​i​l​t​r​o​ ​i​n​s​e​r​i​d​o​.
	 */
	NoRatingOptionsFilter: string
	/**
	 * N​ã​o​ ​e​x​i​s​t​e​m​ ​c​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​p​a​r​a​ ​m​o​s​t​r​a​r​.
	 */
	NoRatingOptionsToShow: string
	/**
	 * N​ã​o​ ​e​x​i​s​t​e​m​ ​i​n​q​u​é​r​i​t​o​s​ ​c​o​m​ ​o​ ​f​i​l​t​r​o​ ​i​n​s​e​r​i​d​o​.
	 */
	NoSurveysFilter: string
	/**
	 * N​ã​o​ ​e​x​i​s​t​e​m​ ​i​n​q​u​é​r​i​t​o​s​ ​p​a​r​a​ ​m​o​s​t​r​a​r​.
	 */
	NoSurveysToShow: string
	/**
	 * S​e​m​ ​t​í​t​u​l​o
	 */
	NoTitle: string
	/**
	 * P​e​r​m​i​s​s​õ​e​s
	 */
	Permissions: string
	/**
	 * P​e​r​m​i​s​s​õ​e​s​ ​g​u​a​r​d​a​d​a​s​ ​c​o​m​ ​s​u​c​e​s​s​o​.
	 */
	PermissionsSaved: string
	PermissionsType: {
		/**
		 * C​r​i​a​r
		 */
		Create: string
		/**
		 * R​e​m​o​v​e​r
		 */
		Delete: string
		/**
		 * A​l​t​e​r​a​r
		 */
		Patch: string
		/**
		 * A​c​e​s​s​a​r
		 */
		Read: string
		/**
		 * E​d​i​t​a​r
		 */
		Update: string
	}
	/**
	 * P​r​é​-​v​i​s​u​a​l​i​z​a​r
	 */
	Preview: string
	/**
	 * D​e​s​c​r​i​ç​ã​o​ ​d​a​ ​q​u​e​s​t​ã​o
	 */
	QuestionDescription: string
	/**
	 * T​í​t​u​l​o​ ​d​a​ ​q​u​e​s​t​ã​o
	 */
	QuestionTitle: string
	/**
	 * T​i​p​o​ ​d​e​ ​q​u​e​s​t​ã​o
	 */
	QuestionType: string
	/**
	 * C​l​a​s​s​i​f​i​c​a​ç​ã​o
	 */
	Rating: string
	/**
	 * D​e​s​c​r​i​ç​ã​o​ ​d​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
	 */
	RatingGroupDescription: string
	/**
	 * I​n​s​i​r​a​ ​u​m​a​ ​d​e​s​c​r​i​ç​ã​o​ ​p​a​r​a​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
	 */
	RatingGroupDescriptionText: string
	/**
	 * D​e​t​a​l​h​e​s​ ​d​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
	 */
	RatingGroupDetails: string
	/**
	 * T​í​t​u​l​o​ ​d​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
	 */
	RatingGroupTitle: string
	/**
	 * I​n​s​i​r​a​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​i​d​e​n​t​i​f​i​c​a​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
	 */
	RatingGroupTitleText: string
	/**
	 * C​r​i​t​é​r​i​o​s​ ​d​e​ ​A​v​a​l​i​a​ç​ã​o
	 */
	RatingGroups: string
	/**
	 * D​e​s​c​r​i​ç​ã​o​ ​d​a​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
	 */
	RatingOptionDescription: string
	/**
	 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​c​o​m​e​n​t​á​r​i​o
	 */
	RatingOptionNeedComment: string
	/**
	 * T​í​t​u​l​o​ ​d​a​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
	 */
	RatingOptionTitle: string
	/**
	 * O​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
	 */
	RatingOptions: string
	/**
	 * V​o​l​t​a​r
	 */
	Return: string
	/**
	 * G​u​a​r​d​a​r
	 */
	Save: string
	/**
	 * M​o​s​t​r​a​r​ ​n​o​ ​i​d​i​o​m​a
	 */
	ShowInLanguage: string
	/**
	 * E​x​i​b​i​n​d​o​ ​{​f​i​r​s​t​E​l​e​m​e​n​t​}​ ​a​t​é​ ​{​l​a​s​t​E​l​e​m​e​n​t​}​ ​d​e​ ​{​t​o​t​a​l​}​ ​i​t​e​n​s
	 * @param {number} firstElement
	 * @param {number} lastElement
	 * @param {number} total
	 */
	ShowItemsLabel: RequiredParams<'firstElement' | 'lastElement' | 'total'>
	/**
	 * E​s​t​a​t​í​s​t​i​c​a​s
	 */
	Statistics: string
	Status: {
		/**
		 * A​t​i​v​o​s
		 */
		Active: string
		/**
		 * C​a​n​c​e​l​a​d​o​s
		 */
		Canceled: string
		/**
		 * C​o​m​p​l​e​t​o​s
		 */
		Completed: string
		/**
		 * N​ã​o​ ​I​n​i​c​i​a​d​o​s
		 */
		NotStarted: string
	}
	Steps: {
		/**
		 * A​t​i​v​a​r
		 */
		Activate: string
		/**
		 * D​e​t​a​l​h​e​s
		 */
		Details: string
		/**
		 * F​u​n​c​i​o​n​á​r​i​o​s
		 */
		Employees: string
		/**
		 * O​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		RatingOptions: string
		/**
		 * Q​u​e​s​t​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		RatingQuestions: string
		/**
		 * Q​u​e​s​t​i​o​n​á​r​i​o
		 */
		Template: string
		/**
		 * Q​u​e​s​t​õ​e​s​ ​d​e​ ​t​e​x​t​o
		 */
		TextQuestions: string
	}
	/**
	 * S​u​b​m​i​s​s​õ​e​s
	 */
	Submissions: string
	/**
	 * D​e​s​c​r​i​ç​ã​o​ ​d​o​ ​i​n​q​u​é​r​i​t​o
	 */
	SurveyDescription: string
	/**
	 * I​n​s​i​r​a​ ​u​m​a​ ​d​e​s​c​r​i​ç​ã​o​ ​p​a​r​a​ ​o​ ​i​n​q​u​é​r​i​t​o​.
	 */
	SurveyDescriptionText: string
	/**
	 * T​í​t​u​l​o​ ​d​o​ ​i​n​q​u​é​r​i​t​o
	 */
	SurveyTitle: string
	/**
	 * I​n​s​i​r​a​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​i​d​e​n​t​i​f​i​c​a​r​ ​o​ ​i​n​q​u​é​r​i​t​o​.
	 */
	SurveyTitleText: string
	/**
	 * I​n​q​u​é​r​i​t​o​s
	 */
	Surveys: string
	/**
	 * P​á​g​i​n​a​ ​p​a​r​a​ ​c​r​i​a​r​ ​u​m​ ​n​o​v​o​ ​i​n​q​u​é​r​i​t​o​.
	 */
	SurveysDescription: string
	/**
	 * T​e​x​t​o
	 */
	Text: string
	/**
	 * U​t​i​l​i​z​a​d​o​r
	 */
	User: string
}

export type TranslationFunctions = {
	/**
	 * Ações
	 */
	Actions: () => LocalizedString
	/**
	 * Ativar inquérito
	 */
	ActivateSurvey: () => LocalizedString
	/**
	 * Se desejar ativar o inquérito insira um valor para a data de fim do inquérito. Se pretende ativar o inquérito mais tarde basta passar este passo.
	 */
	ActivateSurveyText: () => LocalizedString
	/**
	 * Adicionar questão
	 */
	AddQuestion: () => LocalizedString
	/**
	 * Adicionar opção de classificação
	 */
	AddRatingOption: () => LocalizedString
	/**
	 * Disponível em
	 */
	AvailableInLangs: () => LocalizedString
	/**
	 * Backoffice
	 */
	Backoffice: () => LocalizedString
	/**
	 * Menu de Backoffice
	 */
	BackofficeMenu: () => LocalizedString
	/**
	 * Categorias
	 */
	Categories: () => LocalizedString
	/**
	 * Nesta página estão listadas todas as categorias presentes no sistema, mudando o idioma consegue ver as categories disponível no idioma selecionado e pode também filtrar as categorias inserindo parte do título da categoria na barra de pesquisa.
	 */
	CategoriesPageDescription: () => LocalizedString
	/**
	 * Descrição da categoria
	 */
	CategoryDescription: () => LocalizedString
	/**
	 * Insira uma descrição para a categoria.
	 */
	CategoryDescriptionText: () => LocalizedString
	/**
	 * Detalhes da categoria
	 */
	CategoryDetails: () => LocalizedString
	/**
	 * Questões da categoria
	 */
	CategoryQuestions: () => LocalizedString
	/**
	 * Título da categoria
	 */
	CategoryTitle: () => LocalizedString
	/**
	 * Insira um título para identificar a categoria.
	 */
	CategoryTitleText: () => LocalizedString
	/**
	 * Selecionar perfil
	 */
	ChooseProfile: () => LocalizedString
	/**
	 * Selecione o perfil ao qual deseja alterar as permissões.
	 */
	ChooseProfileText: () => LocalizedString
	/**
	 * Confirmar
	 */
	Confirm: () => LocalizedString
	/**
	 * Continuar
	 */
	Continue: () => LocalizedString
	/**
	 * Criar categoria
	 */
	CreateCategory: () => LocalizedString
	/**
	 * Página para criar uma nova categoria.
	 */
	CreateCategoryDescription: () => LocalizedString
	/**
	 * Criação de questões de classificação
	 */
	CreateQuestionsOfRatingLabel: () => LocalizedString
	/**
	 * Passo para criar questões de classificação para a categoria que está a ser criada. Pode saltar este passo caso a categoria só tenha questões de texto.
	 */
	CreateQuestionsOfRatingText: () => LocalizedString
	/**
	 * Criação de questões de texto
	 */
	CreateQuestionsOfTextLabel: () => LocalizedString
	/**
	 * Passo para criar questões de texto para a categoria que está a ser criada. Pode saltar este passo caso a categoria só tenha questões de classificação.
	 */
	CreateQuestionsOfTextText: () => LocalizedString
	/**
	 * Criar critério de avaliação
	 */
	CreateRatingGroup: () => LocalizedString
	/**
	 * Página para criar um novo critério de avaliação.
	 */
	CreateRatingGroupDescription: () => LocalizedString
	/**
	 * Criar opções de classificação
	 */
	CreateRatingOptions: () => LocalizedString
	/**
	 * Passo para criação das opções de classificação associadas ao critério de avaliação.
	 */
	CreateRatingOptionsText: () => LocalizedString
	/**
	 * Criar inquérito
	 */
	CreateSurvey: () => LocalizedString
	/**
	 * Página para criar um novo inquérito.
	 */
	CreateSurveyDescription: () => LocalizedString
	/**
	 * Criada por
	 */
	CreatedBy: () => LocalizedString
	/**
	 * Erro ao tentar criar a categoria.
	 */
	CreatedCategoryFailed: () => LocalizedString
	/**
	 * Já existe uma categoria com o mesmo título.
	 */
	CreatedCategorySameTitle: () => LocalizedString
	/**
	 * Categoria criada com sucesso.
	 */
	CreatedCategorySaved: () => LocalizedString
	/**
	 * Erro ao tentar criar o critério de avaliação.
	 */
	CreatedRatingGroupFailed: () => LocalizedString
	/**
	 * Já existe um critério de avaliação com o mesmo título.
	 */
	CreatedRatingGroupSameTitle: () => LocalizedString
	/**
	 * Critério de avaliação criado com sucesso.
	 */
	CreatedRatingGroupSaved: () => LocalizedString
	/**
	 * Erro ao tentar criar o inquérito.
	 */
	CreatedSurveyFailed: () => LocalizedString
	/**
	 * Já existe um inquérito com o mesmo título.
	 */
	CreatedSurveySameTitle: () => LocalizedString
	/**
	 * Inquérito criado com sucesso.
	 */
	CreatedSurveySaved: () => LocalizedString
	/**
	 * Remover
	 */
	Delete: () => LocalizedString
	/**
	 * Remover categoria
	 */
	DeleteCategory: () => LocalizedString
	/**
	 * Tem a certeza que pretende remover esta categoria? Esta ação não pode ser revertida.
	 */
	DeleteCategoryAlertText: () => LocalizedString
	/**
	 * Erro ao tentar remover a categoria.
	 */
	DeleteCategoryFailed: () => LocalizedString
	/**
	 * Categoria removida com sucesso.
	 */
	DeleteCategorySaved: () => LocalizedString
	/**
	 * Esta ação irá remover a categoria de forma permanente. Verifique se deseja mesmo remover a categoria.
	 */
	DeleteCategoryText: () => LocalizedString
	/**
	 * Remover questão
	 */
	DeleteQuestion: () => LocalizedString
	/**
	 * Remover critério de avaliação
	 */
	DeleteRatingGroup: () => LocalizedString
	/**
	 * Tem a certeza que pretende remover este critério de avaliação? Esta ação não pode ser revertida.
	 */
	DeleteRatingGroupAlertText: () => LocalizedString
	/**
	 * Erro ao tentar remover o critério de avaliação.
	 */
	DeleteRatingGroupFailed: () => LocalizedString
	/**
	 * Critério de avaliação removido com sucesso.
	 */
	DeleteRatingGroupSaved: () => LocalizedString
	/**
	 * Esta ação irá remover o critério de avaliação de forma permanente. Verifique se deseja mesmo remover o critério de avaliação.
	 */
	DeleteRatingGroupText: () => LocalizedString
	/**
	 * Remover opção de classificação
	 */
	DeleteRatingOption: () => LocalizedString
	/**
	 * Remover inquérito
	 */
	DeleteSurvey: () => LocalizedString
	/**
	 * Tem a certeza que pretende remover o inquérito? Esta ação não pode ser revertida.
	 */
	DeleteSurveyAlertText: () => LocalizedString
	/**
	 * Erro ao tentar remover o inquérito.
	 */
	DeleteSurveyFailed: () => LocalizedString
	/**
	 * Inquérito removido com sucesso.
	 */
	DeleteSurveySaved: () => LocalizedString
	/**
	 * Editar
	 */
	Edit: () => LocalizedString
	/**
	 * Editar categoria
	 */
	EditCategory: () => LocalizedString
	/**
	 * Tem a certeza que pretende editar esta categoria?
	 */
	EditCategoryAlertText: () => LocalizedString
	/**
	 * Nesta página pode realizar a edição de uma categoria e das suas questões desde que esta não esteja a ser utilizada em avaliações.
	 */
	EditCategoryDescription: () => LocalizedString
	/**
	 * Esta ação irá permiti-lo editar a categoria. Poderá alterar o título, a descrição e as questões da categoria.
	 */
	EditCategoryText: () => LocalizedString
	/**
	 * Edição de questões de classificação
	 */
	EditQuestionsOfRatingLabel: () => LocalizedString
	/**
	 * Passo para editar questões de classificação para a categoria que está a ser editada. Pode saltar este passo caso queira saltar a edição das questões de classificação.
	 */
	EditQuestionsOfRatingText: () => LocalizedString
	/**
	 * Edição de questões de texto
	 */
	EditQuestionsOfTextLabel: () => LocalizedString
	/**
	 * Passo para editar questões de texto para a categoria que está a ser editada. Pode saltar este passo caso queira saltar a edição das questões de texto.
	 */
	EditQuestionsOfTextText: () => LocalizedString
	/**
	 * Editar critério de avaliação
	 */
	EditRatingGroup: () => LocalizedString
	/**
	 * Tem a certeza que pretende editar este critério de avaliação?
	 */
	EditRatingGroupAlertText: () => LocalizedString
	/**
	 * Esta ação irá permiti-lo editar o critério de avaliação. Poderá alterar o título, descrição e as opções de classificação.
	 */
	EditRatingGroupText: () => LocalizedString
	/**
	 * Editar opções de classificação
	 */
	EditRatingOptions: () => LocalizedString
	/**
	 * Passo onde pode editar as opções de classificação deste critério. Pode editar ou remover opções existentes, ou criar novas.
	 */
	EditRatingOptionsText: () => LocalizedString
	/**
	 * Erro ao tentar editar a categoria.
	 */
	EditedCategoryFailed: () => LocalizedString
	/**
	 * Categoria editada com sucesso.
	 */
	EditedCategorySaved: () => LocalizedString
	/**
	 * Erro ao tentar editar o critério de avaliação
	 */
	EditedRatingGroupFailed: () => LocalizedString
	/**
	 * Critério de avaliação editado com sucesso.
	 */
	EditedRatingGroupSaved: () => LocalizedString
	/**
	 * Erro
	 */
	Error: () => LocalizedString
	ErrorType: {
		/**
		 * Não é possível guardar as permissões deste perfil.
		 */
		CannotSavePermissions: () => LocalizedString
		/**
		 * Erro ao carregar as categorias.
		 */
		Categories: () => LocalizedString
		/**
		 * Necessita de inserir um título para a categoria em {language}.
		 */
		NoCategoryTitle: (arg: { language: unknown }) => LocalizedString
		/**
		 * Necessita de selecionar pelo menos um idioma.
		 */
		NoLanguagesChoice: () => LocalizedString
		/**
		 * Necessita de inserir pelo menos uma questão.
		 */
		NoQuestions: () => LocalizedString
		/**
		 * Não foram encontradas permissões para mostrar.
		 */
		NoPermissionsOfProfile: () => LocalizedString
		/**
		 * Não foram encontrados perfis para mostrar.
		 */
		NoProfiles: () => LocalizedString
		/**
		 * Necessita de inserir um título para o critério de avaliação.
		 */
		NoRatingGroupTitle: () => LocalizedString
		/**
		 * Necessita de inserir um título para a questão do tipo de clasificação em {language}.
		 */
		NoRatingQuestionTitle: (arg: { language: unknown }) => LocalizedString
		/**
		 * Necessita de inserir um título para o inquérito.
		 */
		NoSurveyTitle: () => LocalizedString
		/**
		 * Necessita de inserir um título para a questão do tipo de texto em {language}.
		 */
		NoTextQuestionTitle: (arg: { language: unknown }) => LocalizedString
		/**
		 * Erro ao carregar os critérios de avaliação.
		 */
		RatingGroups: () => LocalizedString
		/**
		 * Erro ao carregar os inquéritos.
		 */
		Surveys: () => LocalizedString
	}
	/**
	 * Finalizar
	 */
	Finalize: () => LocalizedString
	/**
	 * Avançar
	 */
	Forward: () => LocalizedString
	/**
	 * Frontoffice
	 */
	Frontoffice: () => LocalizedString
	/**
	 * Menu de Frontoffice
	 */
	FrontofficeMenu: () => LocalizedString
	/**
	 * Olá
	 */
	Hello: () => LocalizedString
	/**
	 * Início
	 */
	Home: () => LocalizedString
	/**
	 * Filtrar categorias pelo título
	 */
	InputCategory: () => LocalizedString
	/**
	 * Filtrar critérios de avaliação pelo título
	 */
	InputRatingGroup: () => LocalizedString
	/**
	 * Filtrar inquérito pelo título
	 */
	InputSurvey: () => LocalizedString
	Language: {
		/**
		 * Português
		 */
		PT: () => LocalizedString
		/**
		 * Inglês
		 */
		EN: () => LocalizedString
		/**
		 * Espanhol
		 */
		ES: () => LocalizedString
		/**
		 * Francês
		 */
		FR: () => LocalizedString
		/**
		 * Polaco
		 */
		PL: () => LocalizedString
	}
	/**
	 * Selecione para quais idiomas deseja criar a categoria.
	 */
	LanguageChoiceCategoryDescription: () => LocalizedString
	/**
	 * Selecione para quais idiomas deseja criar o critério de avaliação.
	 */
	LanguageChoiceRatingGroupDescription: () => LocalizedString
	/**
	 * Selecione o(s) idioma(s)
	 */
	LanguageChoiceTitle: () => LocalizedString
	/**
	 * A Carregar
	 */
	Loading: () => LocalizedString
	/**
	 * Não existem ações disponíveis.
	 */
	NoActionsAvailable: () => LocalizedString
	/**
	 * Não existem categorias com o filtro inserido.
	 */
	NoCategoriesFilter: () => LocalizedString
	/**
	 * Não existem categorias para mostrar.
	 */
	NoCategoriesToShow: () => LocalizedString
	/**
	 * Sem descrição
	 */
	NoDescription: () => LocalizedString
	/**
	 * Sem login
	 */
	NoLogin: () => LocalizedString
	/**
	 * Necessita de realizar o login antes de acessar esta página.
	 */
	NoLoginText: () => LocalizedString
	/**
	 * Utilizador sem perfil
	 */
	NoProfileUser: () => LocalizedString
	/**
	 * Não tem um perfil associado á sua conta, seja frontoffice ou backoffice. Tente solucionar este problema antes de acessar a página novamente.
	 */
	NoProfileUserText: () => LocalizedString
	/**
	 * Não existem critérios de avaliação com o filtro inserido.
	 */
	NoRatingOptionsFilter: () => LocalizedString
	/**
	 * Não existem critérios de avaliação para mostrar.
	 */
	NoRatingOptionsToShow: () => LocalizedString
	/**
	 * Não existem inquéritos com o filtro inserido.
	 */
	NoSurveysFilter: () => LocalizedString
	/**
	 * Não existem inquéritos para mostrar.
	 */
	NoSurveysToShow: () => LocalizedString
	/**
	 * Sem título
	 */
	NoTitle: () => LocalizedString
	/**
	 * Permissões
	 */
	Permissions: () => LocalizedString
	/**
	 * Permissões guardadas com sucesso.
	 */
	PermissionsSaved: () => LocalizedString
	PermissionsType: {
		/**
		 * Criar
		 */
		Create: () => LocalizedString
		/**
		 * Remover
		 */
		Delete: () => LocalizedString
		/**
		 * Alterar
		 */
		Patch: () => LocalizedString
		/**
		 * Acessar
		 */
		Read: () => LocalizedString
		/**
		 * Editar
		 */
		Update: () => LocalizedString
	}
	/**
	 * Pré-visualizar
	 */
	Preview: () => LocalizedString
	/**
	 * Descrição da questão
	 */
	QuestionDescription: () => LocalizedString
	/**
	 * Título da questão
	 */
	QuestionTitle: () => LocalizedString
	/**
	 * Tipo de questão
	 */
	QuestionType: () => LocalizedString
	/**
	 * Classificação
	 */
	Rating: () => LocalizedString
	/**
	 * Descrição do critério de avaliação
	 */
	RatingGroupDescription: () => LocalizedString
	/**
	 * Insira uma descrição para o critério de avaliação.
	 */
	RatingGroupDescriptionText: () => LocalizedString
	/**
	 * Detalhes do critério de avaliação
	 */
	RatingGroupDetails: () => LocalizedString
	/**
	 * Título do critério de avaliação
	 */
	RatingGroupTitle: () => LocalizedString
	/**
	 * Insira um título para identificar o critério de avaliação.
	 */
	RatingGroupTitleText: () => LocalizedString
	/**
	 * Critérios de Avaliação
	 */
	RatingGroups: () => LocalizedString
	/**
	 * Descrição da opção de classificação
	 */
	RatingOptionDescription: () => LocalizedString
	/**
	 * Necessita de comentário
	 */
	RatingOptionNeedComment: () => LocalizedString
	/**
	 * Título da opção de classificação
	 */
	RatingOptionTitle: () => LocalizedString
	/**
	 * Opções de classificação
	 */
	RatingOptions: () => LocalizedString
	/**
	 * Voltar
	 */
	Return: () => LocalizedString
	/**
	 * Guardar
	 */
	Save: () => LocalizedString
	/**
	 * Mostrar no idioma
	 */
	ShowInLanguage: () => LocalizedString
	/**
	 * Exibindo {firstElement} até {lastElement} de {total} itens
	 */
	ShowItemsLabel: (arg: { firstElement: number, lastElement: number, total: number }) => LocalizedString
	/**
	 * Estatísticas
	 */
	Statistics: () => LocalizedString
	Status: {
		/**
		 * Ativos
		 */
		Active: () => LocalizedString
		/**
		 * Cancelados
		 */
		Canceled: () => LocalizedString
		/**
		 * Completos
		 */
		Completed: () => LocalizedString
		/**
		 * Não Iniciados
		 */
		NotStarted: () => LocalizedString
	}
	Steps: {
		/**
		 * Ativar
		 */
		Activate: () => LocalizedString
		/**
		 * Detalhes
		 */
		Details: () => LocalizedString
		/**
		 * Funcionários
		 */
		Employees: () => LocalizedString
		/**
		 * Opções de classificação
		 */
		RatingOptions: () => LocalizedString
		/**
		 * Questões de classificação
		 */
		RatingQuestions: () => LocalizedString
		/**
		 * Questionário
		 */
		Template: () => LocalizedString
		/**
		 * Questões de texto
		 */
		TextQuestions: () => LocalizedString
	}
	/**
	 * Submissões
	 */
	Submissions: () => LocalizedString
	/**
	 * Descrição do inquérito
	 */
	SurveyDescription: () => LocalizedString
	/**
	 * Insira uma descrição para o inquérito.
	 */
	SurveyDescriptionText: () => LocalizedString
	/**
	 * Título do inquérito
	 */
	SurveyTitle: () => LocalizedString
	/**
	 * Insira um título para identificar o inquérito.
	 */
	SurveyTitleText: () => LocalizedString
	/**
	 * Inquéritos
	 */
	Surveys: () => LocalizedString
	/**
	 * Página para criar um novo inquérito.
	 */
	SurveysDescription: () => LocalizedString
	/**
	 * Texto
	 */
	Text: () => LocalizedString
	/**
	 * Utilizador
	 */
	User: () => LocalizedString
}

export type Formatters = {}
